### ISSUE TITLE
You are scum

### ISSUE THREAD

**Issue by Krishun** [tomkahn/lockmyphone_public#1]
You extorted my phone for 2.99?  You locked my phone for 24 hours, and extorted me to unlock it for 2.99?  You piece of shit! You had an app that did exactly what I needed, and your greedy, criminal ass decided to rip off your loyal customer.  Rot in hell, you garbage pail!

**Comment by tomkahn** [comment]
I'm not sure what you're upset about. You can disable the pay to unlock feature in the options if you prefer that. Certainly you're not angry that an app called "Lock My Phone" actually _locks your phone,_ are you?

Anyway, instead of screeching like an idiot you might want to send me your order number and ask for a refund. I'm not interested in your money. Invest it in a course on manners instead.

Best,
Thomas
