### ISSUE TITLE
SCAM: do not use this application

### ISSUE THREAD

**Issue by Krishun** [tomkahn/lockmyphone_public#2]
For the benefit of others that will run into this scam, I'll detail how the developer can extorts your phone. He'll pretend he doesn't know what you're talking about.

I turned on my phone, only to find that Lock Your Phone had "conveniently" locked my phone for 24 hours. I have had no such lock period scheduled on my phone. When I could later access the app, there was no new 24 lock period in my schedule.

Not only was my phone locked out for 24 hours, there was this new "please pay $2.99" to unlock your phone, double tap here". This application has administrative privileges, there is no way to bypass the app. So essentially, unless I wanted to wait 24 hours without a phone, I had to pay this criminal. 

The developer pushed an update to this app that locks the device for 24 and extorts the user to pay to get access to their own hardware. It's a great scam, you can't even take a screenshot of the extorting message from the lock screen.

Used to be the perfect application, but obviously greed got in the way. Stay away!

**Comment by tomkahn** [comment]
I don't pretend to not know what you are talking about, I really don't know!

If your phone was locked without you adding such a lock period, then this is a bug. So far you are the only one to report such problems since the pay to unlock feature was introduced. You can disable the pay to unlock feature in the settings by the way.

Also, the maximum length of a lock period is 12 hours, so it's especially weird that you reported it said your phone was locked for 24 hours.

I offered to refund your money, even though you are behaving in an insulting and libelous way. There is nothing more I can do.
